###
GET localhost:10001/acb/transaction/all


###
POST localhost:10001/acb/es/transaction
Content-Type: application/json

{
  "userId": "a",
  "userName": "안녕하세요 오늘은 그냥 이렇게 테스트를 해보려고 합니다",
  "amt": 10000
}

### 저장된 단일 데이터 조회
GET localhost:9200/transaction/_doc/a

### 저장된 모든 인덱스 내에 저장된 데이터 조회
GET localhost:9200/transaction/_search

### 리스트 저장
POST localhost:10001/acb/es/transaction/list
Content-Type: application/json

[
  {
    "userId": "a",
    "userName": "안녕하세요 오늘은 그냥 이렇게 테스트를 해보려고 합니다",
    "amt": 10000
  },
  {
    "userId": "bbb",
    "userName": "할롱 할롱 할롱",
    "amt": 5000
  }
]


### 리스트 저장
POST localhost:10001/acb/es/transaction/list
Content-Type: application/json

[
  {
    "userId": "a",
    "userName": "안녕하세요 오늘은 그냥 이렇게 테스트를 해보려고 합니다",
    "amt": 10000
  },
  {
    "userId": "bbb",
    "userName": "할롱 할롱 할롱",
    "amt": 5000
  }
]

### ES 단일 조회
POST localhost:9200/transaction/_search?q=id:bbb

### ES 조건상관없이 전체 조회
GET localhost:9200/transaction/_search


### ES index 정보 조회
PUT localhost:9200/transaction/_docs


### ES querying
GET localhost:9200/transaction/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "name": "할롱"
    }
  }
}

### ES @Query
GET localhost:10001/acb/es/transaction/name/할롱

### ES Avg
GET localhost:10001/acb/es/transaction/avg


###
# curl -X POST "http://localhost:5601/api/saved_objects/_create" -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '
#{
# "attributes": {
# "title": "Your Saved Search Title",
# "description": "Your Saved Search Description",
# "searchSourceJSON": "{\"index\":\"your-index-pattern-id\",\"query\":{\"query\":\"your-query\"},\"filter\":[]}"
# },
# "type": "search"
#}'
POST http://localhost:5601/api/saved_objects/search
kbn-xsrf: true
Content-Type: application/json

{
  "attributes": {
    "title": "Your Saved Search Title",
    "description": "Your Saved Search Description",
    "kibanaSavedObjectMeta": {
      "searchSourceJSON": {
        "index": "transaction",
        "query": {},
        "filter": []
      }
    }
  }
}

###






























